### PR TITLE
Handle failure to communicate with npm gracefully

### LINKED ISSUE #72: Handle missing Internet connection more gracefully
@marzipankaiser opened a fresh VSCode instance without an internet connection and saw this:

Image

Note that everything still works correctly [!], go to definition, etc., just the error output is weird and misleading (again, LSP works, but the error indicates otherwise?)

```
[2025-05-07T13:37:05.130Z] INFO: Located executable at custom path effekt with version 0.24.0
[2025-05-07T13:37:05.537Z] ERROR: Failed to check Effekt: Error: Failed to fetch latest version from npm: Error: getaddrinfo ENOTFOUND registry.npmjs.org
[2025-05-07T13:37:05.781Z] INFO: Located executable at custom path effekt with version 0.24.0
```

### PR DESCRIPTION
**Pull request by marzipankaiser**
Fixes #72 by printing a more useful message.

If Effekt can be found locally:
Screenshot 2025-05-19 at 14 43 36

if it can't:
Screenshot 2025-05-19 at 15 54 23

### CODE REVIEW

File: src/effektManager.ts [hunk 1]
```diff
@@ -393,10 +393,24 @@ export class EffektManager {
       const currentVersion = await this.getEffektVersion();
       const latestVersion = await this.getLatestNPMVersion(
         this.effektNPMPackage,
-      );
+      ).catch(function (_err: string) {
+        return null;
+      });
```
Comment (jiribenes) [inline src/effektManager.ts:398]: This now means that all of the errors caused by `latestVersion` failing will "silently" fail with `null`.
Doesn't that influence the `catch` block underneath?

Comment (jiribenes) [reply src/effektManager.ts:398]: (In different words: shouldn't this fix go directly to `getLatestNPMVersion`?)

Comment (marzipankaiser) [reply src/effektManager.ts:398]: The catch block below either:
- offers to install, which will very likely fail if getting the version from npm doesn't even work, or
- just errors out.

Comment (jiribenes) [reply src/effektManager.ts:398]: I guess that's true, yes.
It's just that we're mixing multiple try-catch blocks in different styles:
`try { ...; promise().catch { _ => null }; ... } catch { e => ... }`

Comment (marzipankaiser) [reply src/effektManager.ts:398]: We could directly return a nullable, if that's what you mean?

Otherwise: On some level, we do need to handle it here to decide between "installed/not installed"

**Comment by JakubSchwenkbeck** [comment]
Are the ESLint fixes annoying? -> is there something wrong with our setup (does  `npm run lint:fix`  not work properly? )

File: src/effektManager.ts [hunk 2]
```diff
@@ -391,33 +391,67 @@ export class EffektManager {
...
+          );
+          return currentVersion;
+        } else {
+          throw error; // rethrow
+        }
+      }
     } catch (error) {
       if (
         error instanceof Error &&
         error.message.includes('Effekt executable not found')
```
Comment (timsueberkrueb) [inline src/effektManager.ts:434]: We should really use a separate error class for this, I don't know in which review this slipped through.

File: src/effektManager.ts [hunk 3]
```diff
@@ -391,33 +391,67 @@ export class EffektManager {
...
-        return this.promptForAction(latestVersion, 'install', client);
+        try {
+          const latestVersion = await this.getLatestNPMVersion(
+            this.effektNPMPackage,
+          );
+          return this.promptForAction(latestVersion, 'install', client);
+        } catch (error) {
+          if (
+            error instanceof Error &&
+            error.message.includes('Failed to fetch latest version from npm')
```
Comment (timsueberkrueb) [inline src/effektManager.ts:444]: Declare error classes and throw the appropriate instance.

File: src/effektManager.ts [hunk 4]
```diff
@@ -391,33 +391,67 @@ export class EffektManager {
...
+          );
+        }
+
+        this.updateStatusBar();
+        return this.effektVersion || '';
+      } catch (error) {
+        if (
+          currentVersion &&
+          error instanceof Error &&
+          error.message.includes('Failed to fetch latest version from npm')
```
Comment (timsueberkrueb) [inline src/effektManager.ts:417]: Declare error classes and throw the appropriate instance.

**Review by timsueberkrueb — CHANGES_REQUESTED** [review]

**Comment by marzipankaiser** [comment]
@JakubSchwenkbeck I didn't know to `npm run lint:fix` (and didn't try to find it, since it's a small PR and I didn't want to spend a lot of time on it).
I'll try for the next changes.

**Review by timsueberkrueb — APPROVED** [review]
Fantastic, thank you!
Checked that it works on Ubuntu 24.04.
